DROP USER deepfakenewsERS CASCADE;

CREATE USER deepfakenewsERS
IDENTIFIED BY RR1lFw6Ll8bbyBXRfwQTQ
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA 10M ON users;

GRANT CONNECT TO deepfakenewsERS;
GRANT RESOURCE TO deepfakenewsERS;
GRANT CREATE SESSION TO deepfakenewsERS;
GRANT CREATE TABLE TO deepfakenewsERS;
GRANT CREATE VIEW TO deepfakenewsERS;

conn deepfakenewsERS/RR1lFw6Ll8bbyBXRfwQTQ;